package com.baize.common_lib;

public class Constants {
    public static final String TOPIC_CALL = "ocamar_call_info_topic";  //呼叫相关
    public static final String TOPIC_CALL_INFO = "ocamar/call/info";  //呼叫推送 #exchange_ocamar_dwmws_call_info_topic
    public static final String TOPIC_RECEIVESERVICE_CALLPATIENTFAMILY = "ocamar/receiveservice/callPatientFamily"; //呼叫家属推送 #ocamar.receiveservice.exchange
    public static final String TOPIC_BEDTOP_IOT_VITAL = "ocamar/bedtop/iot/vital"; //物联网数据推送（床头） #exchange_ocamar_dwmws_IOT_bedtop_topic
    public static final String TOPIC_SIDEBED_IOT_VITAL = "ocamar/sidebed/iot/vital"; //物联网数据推送（床旁） #exchange_ocamar_dwmws_iot_sidebed_topic
    public static final String TOPIC_DOORWAY_IOT_VITAL = "ocamar/doorway/iot/vital"; //物联网数据推送（门口） #exchange_ocamar_dwmws_IOT_doorway_topic
    public static final String TOPIC_INTERACTIVE_IOT_VITAL = "ocamar/interactive/iot/vital"; //物联网数据推送（交互屏） #exchange_ocamar_dwmws_IOT_doorway_topic
    public static final String TOPIC_IOT_MEDICALINSTRUMENT = "ocamar/iot/medicalinstrument"; //点测数据推送（综合） #ocamar.receiveservice.exchange
    public static final String TOPIC_APP_UPGRADE = "ocamar/app/upgrade"; //app升级/回退推送 #APP_UPDATE_EXCHANGE #exchange_ocamar_dwmws_app_upgrade_topic
    public static final String TOPIC_CALL_VISIT = "ocamar/call/visit"; //探视呼叫信息推送 #exchange_ocamar_dwmws_call_topic
    public static final String TOPIC_PUSH_BILL = "ocamar/push/bill"; //费用提醒推送 #exchange_ocamar_dwmws_bed_side_topic
    public static final String TOPIC_PUSH_INSPECT = "ocamar/push/inspect"; //检验检查提醒 #exchange_ocamar_dwmws_bed_side_topic
    public static final String TOPIC_PUSH_MED = "ocamar/push/med"; //用药提醒 #exchange_ocamar_dwmws_bed_side_topic
    public static final String TOPIC_PUSH_SURGICAL = "ocamar/push/surgical"; //手术提醒 #exchange_ocamar_dwmws_bed_side_topic
    public static final String TOPIC_IOT_WARNING = "ocamar/iot/warning"; //物联网数据预警设置 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_SCREEN_STYLE = "ocamar/screen/style"; //样式更新 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_BASE_CONFIG = "ocamar/base/config"; //基本设置更新-通用 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_OTHER_SETTING = "ocamar/other/setting"; //基本设置更新-息屏时间和点测数据上传时间 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_INTERACTIVE_IOT_DISPLAY = "ocamar/interactive/iot/display"; //"基本设置更新-物联网综合看板展示数据" #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_IOT_VIEW = "ocamar/iot/view"; //"基本设置更新-物联网体征数据" #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_SIDEBED_MULTI_BED = "ocamar/sidebed/multi/bed"; //"基本设置更新-床旁多床位配置" #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_SIDEBED_VISIT = "ocamar/sidebed/visit"; //"基本设置更新-床旁探视配置" #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_NURSING_STATION_PATIENT_CARD = "ocamar/nursing/station/patient/card"; //"基本设置更新-护士站主机床位卡数据配置" #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_INTERACTIVE_BOTTOM_NAVIGATION = "ocamar/interactive/bottom/navigation"; //"基本设置更新-交互屏底部导航栏筛选内容" #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_INTERACTIVE_PATIENT_CARD = "ocamar/interactive/patient/card"; //"基本设置更新-交互屏患者卡片" #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_INTERACTIVE_PATIENT_IDENTIFY = "ocamar/interactive/patient/identify"; //"基本设置更新-交互屏患者特殊标识" #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_INTERACTIVE_BACKGROUND = "ocamar/interactive/background"; //交互屏个性化背景设置 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_SCREEN_RESTART = "ocamar/screen/restart/%s"; //定时重启 #exchange_ocamar_dwmws_base_topic #{udid}
    public static final String TOPIC_SCREEN_AUDIO = "ocamar/screen/audio/%s"; //声音设置 #exchange_ocamar_dwmws_base_topic #{udid}
    public static final String TOPIC_SCREEN_LOGO = "ocamar/screen/logo"; //logo更新 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_PUSH_EDUCATION = "ocamar/push/education"; //宣教推送 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_PUSH_APP_MODULE = "ocamar/push/app/module"; //屏页面模块更新 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_BACKGROUND_MUSIC = "ocamar/background/music"; //背景音乐推送 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_SCREEN_SOUND_BRIGHT_CONFIG = "ocamar/screen/sound/bright/config/%s"; //亮度声音息屏配置 #exchange_ocamar_dwmws_base_topic #{udid}
    public static final String TOPIC_SCREEN_BACKGROUND_VOLUME_CONFIG = "ocamar/screen/background/volume/config"; //背景音乐音量 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_NOTICE_CONFIG = "ocamar/notice/config"; //公告/病区服务/护理提示推送 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_SIDEBED_FUNCTION = "ocamar/sidebed/function"; //床旁屏功能 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_DOOR_LIGHT_SETTING = "ocamar/door/light/setting"; //门灯开关配置 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_PATIENT_IDENTIFY_CONFIG = "ocamar/patient/identify/config"; //患者护理标识颜色配置 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_SURGICAL_NURSE_RECEIVE_NOTICE = "ocamar/surgical/nurse/receive/notice"; //手术室系统护工接送推送 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_NURSE_JOB_TIMEOUT = "ocamar/nurse/job/timeout"; //护理任务超时提醒 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_HALLWAY_CALL_CONFIG = "ocamar/hallway/call/config/%s"; //走廊屏增援呼叫配置 #exchange_ocamar_dwmws_base_topic #{udid}
    public static final String TOPIC_BEDSIDE_STYLE = "ocamar/bedside/style"; //床头屏样式五配置 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_ROOM_SERVICE = "ocamar/room/service"; //病区病房服务 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_INTERACTIVE_MESSAGE = "ocamar/interactive/message"; //交互屏弹层消息(告警消息更新提醒) #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_SMART_MONITOR_MESSAGE = "ocamar/smart/monitor/message"; //智能设备监测告警推送 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_NURSING_MESSAGE = "ocamar/nursing/message"; //护理留言推送 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_FEE_NOTICE = "ocamar/fee/notice"; //床旁屏费用提醒（出院、封账） #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_HAND_WASH_NOTICE = "ocamar/hand/wash/notice"; //手卫生洗手推送 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_NURSE_LOCATION = "ocamar/nurse/location"; //护士查房位置推送 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_DOCTOR_LOCATION = "ocamar/doctor/location"; //医生查房推送 #
    public static final String TOPIC_AUXILIARY_TIMING = "ocamar/auxiliary/timing"; //辅助计时推送 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_HALLWAY_GROUP_MODIFY = "ocamar/hallway/group/modify/%s"; //走廊屏分组修改 #exchange_ocamar_dwmws_base_topic #{udid}
    public static final String TOPIC_HALLWAY_SLOGAN = "ocamar/hallway/slogan/%s"; //走廊屏标语 #exchange_ocamar_dwmws_base_topic #{udid}
    public static final String TOPIC_BIRTHDAY_WISH = "ocamar/birthday/wish"; //生日祝福 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_OUTING_MESSAGE = "ocamar/outing/message"; //外出状态 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_TIMER_EDUCATION = "ocamar/timer/education"; //定时宣教推送 #exchange_ocamar_dwmws_base_topic
    public static final String TOPIC_VITAL_PREVIEW = "ocamar/vital/preview"; //测量数据预显示推送 #exchange_ocamar_dwmws_pre_view_topic
}
